const $=s=>document.querySelector(s),M=$('#main');
const fd=d=>new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});
const V=()=>JSON.parse(localStorage.getItem('jv')||'{}');
const subs=()=>[...new Set(A.flatMap(a=>a.sub))].sort();
const row=a=>`<article class="row i"><img class="ic" src="icon-${a.sub[0].toLowerCase()}.svg" alt="" width="40" height="40"><div><div class="m">${a.ty} · ${fd(a.d)} · ${a.a.join(', ')}</div><h3><a href="#/article/${a.s}">${a.t}</a></h3><p>${a.abs.slice(0,170)}…</p><div>${a.sub.map(s=>`<a class="tag" href="#/articles?s=${s}">${s}</a>`).join('')}<span class="m">DOI ${a.doi}</span></div></div></article>`;
const cite=a=>`Editorial Staff. (${J.y}). ${a.t}. ${J.n}, ${J.v}(${J.i}), ${a.p}. https://doi.org/${a.doi}`;
const bib=a=>`@article{${a.s.replace(/-/g,'')}${J.y},\n  author  = {Editorial Staff},\n  title   = {${a.t}},\n  journal = {${J.n}},\n  year    = {${J.y}},\n  volume  = {${J.v}},\n  number  = {${J.i}},\n  pages   = {${a.p}},\n  doi     = {${a.doi}}\n}`;
const dl=(n,t)=>{const l=document.createElement('a');l.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));l.download=n;l.click()};
const hero='<img src="hero.svg" alt="An atom rising over the Ethiopian highlands" width="380" height="260">';
const fg=(f,c)=>`<figure><img src="${f}.svg" alt="${c}" loading="lazy"><figcaption>${c}</figcaption></figure>`;
function seo(a){document.querySelectorAll('.sm').forEach(e=>e.remove());if(!a)return;const add=(n,c)=>{const m=document.createElement('meta');m.name=n;m.content=c;m.className='sm';document.head.append(m)};add('citation_title',a.t);add('citation_author','Editorial Staff');add('citation_publication_date',a.d.replace(/-/g,'/'));add('citation_journal_title',J.n);add('citation_doi',a.doi);add('citation_issn',PUB.eissn);add('citation_publisher',PUB.publisher);a.kw.forEach(k=>add('citation_keywords',k));const s=document.createElement('script');s.type='application/ld+json';s.className='sm';s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'ScholarlyArticle',headline:a.t,datePublished:a.d,abstract:a.abs,keywords:a.kw,identifier:a.doi,isPartOf:{'@type':'PublicationIssue',issueNumber:J.i,isPartOf:{'@type':'PublicationVolume',volumeNumber:J.v}}});document.head.append(s)}
const pages={
home(){const f=A[0],l=[...A].sort((a,b)=>b.d.localeCompare(a.d)).slice(0,4);return `<div class="w"><div class="hero"><div><h1>Research that moves Ethiopia forward</h1><p class="l">Peer-reviewed studies of Ethiopia–Russia cooperation in energy, trade, agriculture, industry, technology and diplomacy.</p><form class="sf" id="ms" role="search"><input type="search" name="q" placeholder="Search articles, authors, topics" aria-label="Search"><button class="btn">Search</button></form><div class="quick">Try: <a href="#/articles?q=nuclear">nuclear</a>, <a href="#/articles?q=coffee">coffee</a>, <a href="#/articles?q=scholarships">scholarships</a></div></div>${hero}</div>
<section class="s"><div class="hd"><h2>Current issue</h2><a href="#/issues">All issues</a></div><div class="cur"><div><div class="vol">${J.v}.${J.i}</div><div class="m">Volume ${J.v}, Issue ${J.i}<br>October ${J.y}</div></div><div><div class="m">Featured · ${f.ty}</div><h2><a href="#/article/${f.s}" style="color:inherit">${f.t}</a></h2><p>${f.abs}</p><a class="btn" href="#/article/${f.s}">Read article</a></div></div></section>
<section class="s"><div class="hd"><h2>Latest research</h2><a href="#/articles">View all articles</a></div>${l.map(row).join('')}</section>
<section class="s"><h2>Explore by subject</h2>${subs().map(s=>`<a class="tag" style="font-size:16px;padding:6px 16px" href="#/articles?s=${s}">${s} (${A.filter(a=>a.sub.includes(s)).length})</a>`).join('')}</section>
<section class="s"><h2>The partnership at a glance</h2><div class="gl"><img src="key-numbers.svg" alt="Six key numbers about trade, scholarships and the proposed reactors" loading="lazy"><img src="timeline.svg" alt="Timeline of the partnership from 2017 to 2026" loading="lazy"></div></section>
<section class="s"><h2>Journal by the numbers</h2><div class="num"><div><b>${J.v}</b>Volume</div><div><b>${A.length}</b>Articles</div><div><b>${subs().length}</b>Subjects</div><div><b>${new Set(A.flatMap(a=>a.kw)).size}</b>Keywords</div></div></section>
<section class="s"><h2>News</h2><div class="row"><b>31 March 2026.</b> Ethiopia and Rosatom sign the Strategic Roadmap.</div><div class="row"><b>October 2026.</b> Third Russia–Africa Summit scheduled in Russia.</div><div class="row"><b>Open now.</b> Call for papers for Issue 2. <a href="#/authors">See guidelines</a>.</div></section>
<section class="s"><h2>Editorial board</h2>${board()}</section></div>`},
articles(q){const p=new URLSearchParams(q),t=(p.get('q')||'').toLowerCase(),s=p.get('s')||'',o=p.get('o')||'new',v=V();let r=A.filter(a=>(!s||a.sub.includes(s))&&(!t||(a.t+a.abs+a.kw.join()+a.a.join()+a.sub.join()).toLowerCase().includes(t)));r.sort(o=='az'?(a,b)=>a.t.localeCompare(b.t):o=='read'?(a,b)=>(v[b.s]||0)-(v[a.s]||0):(a,b)=>b.d.localeCompare(a.d));return `<div class="w" style="padding-top:28px"><h1>Articles</h1><form class="sf" id="af" style="flex-wrap:wrap"><input type="search" name="q" value="${p.get('q')||''}" placeholder="Search" aria-label="Search" style="flex:1;min-width:180px"><select name="s" aria-label="Subject"><option value="">All subjects</option>${subs().map(x=>`<option${x==s?' selected':''}>${x}</option>`).join('')}</select><select name="o" aria-label="Sort"><option value="new">Latest</option><option value="read"${o=='read'?' selected':''}>Most read (this browser)</option><option value="az"${o=='az'?' selected':''}>A–Z</option></select><button class="btn">Apply</button></form><p class="m" aria-live="polite">${r.length} of ${A.length} articles. Citation counts appear once articles are indexed.</p>${r.map(row).join('')||'<p>No articles match. Clear the search or choose another subject.</p>'}</div>`},
article(slug){const a=A.find(x=>x.s==slug);if(!a)return '<div class="w"><h1>Article not found</h1><a href="#/articles">Browse all articles</a></div>';const v=V();v[a.s]=(v[a.s]||0)+1;localStorage.setItem('jv',JSON.stringify(v));seo(a);document.title=a.t;const rel=A.filter(x=>x!=a&&x.sub.some(s=>a.sub.includes(s))).slice(0,3);
const body=a.body?a.body.map(b=>b[0]=='fig'?fg(b[1],b[2]):`<h2>${b[0]}</h2>${b[1].startsWith('<')?b[1]:'<p>'+b[1]+'</p>'}`).join(''):`<h2>Key points</h2><ul>${a.k.map(x=>`<li>${x}</li>`).join('')}</ul>${(a.figs||[]).map(f=>fg(f[0],f[1])).join('')}<p class="m">Sample summary based on public reports from 2025–2026. Replace with the full manuscript text.</p>`;
return `<div class="w" style="padding-top:28px"><p class="m"><a href="#/articles">Articles</a> / ${a.ty}</p><div class="cols"><aside class="side"><div><b>Authors</b>${a.a.join(', ')}</div><div><b>Published</b>${fd(a.d)}</div><div><b>Issue</b>Vol. ${J.v}, No. ${J.i}, pp. ${a.p}</div><div><b>DOI (placeholder)</b>${a.doi}</div><div><b>Subjects</b>${a.sub.map(s=>`<a class="tag" href="#/articles?s=${s}">${s}</a>`).join('')}</div><div><b>Keywords</b>${a.kw.join(', ')}</div><div class="noprint"><button class="btn sm" onclick="print()">Download PDF</button> <button class="btn o sm" id="sh">Share</button></div></aside>
<article class="art"><h1>${a.t}</h1><div class="abs"><b>Abstract.</b> ${a.abs}</div><div class="body">${body}</div>
<section class="noprint" style="margin-top:32px"><h2>Cite this article</h2><pre id="ct">${cite(a)}</pre><button class="btn sm" id="cc">Copy APA</button> <button class="btn o sm" id="cb">Download BibTeX</button></section>
<section class="noprint"><h2>Related articles</h2>${(rel.length?rel:A.filter(x=>x!=a).slice(0,3)).map(row).join('')}</section></article></div></div>`},
issues(){return `<div class="w" style="padding-top:28px"><h1>Issues</h1><h2>Volume ${J.v}, Issue ${J.i} (Current, October ${J.y})</h2>${A.map(row).join('')}<h2 style="margin-top:32px">Volume ${J.v}, Issue 2 (forthcoming)</h2><p>Open for submissions. <a href="#/authors">See author guidelines</a>.</p></div>`},
explore(){const au=[...new Set(A.flatMap(a=>a.a))],kw={};A.forEach(a=>a.kw.forEach(k=>kw[k]=(kw[k]||0)+1));return `<div class="w" style="padding-top:28px"><h1>Explore</h1><h2>Subjects</h2>${subs().map(s=>`<a class="tag" href="#/articles?s=${s}">${s} (${A.filter(a=>a.sub.includes(s)).length})</a>`).join('')}<h2 style="margin-top:28px">Keywords</h2>${Object.keys(kw).sort().map(k=>`<a class="tag" href="#/articles?q=${encodeURIComponent(k)}">${k}</a>`).join('')}<h2 style="margin-top:28px">Authors</h2>${au.map(x=>`<a class="tag" href="#/articles?q=${encodeURIComponent(x)}">${x}</a>`).join('')}<h2 style="margin-top:28px">Collections and special issues</h2><div class="row"><h3><a href="#/articles?s=Energy">Nuclear and energy transition</a></h3><p>Articles on the Rosatom partnership, skills and policy.</p></div><div class="row"><h3><a href="#/articles?s=Trade">Trade and agriculture</a></h3><p>Coffee, fertilizer and farm inputs.</p></div></div>`},
about(){return `<div class="w" style="padding-top:28px"><h1>About the journal and the writer.</h1><p style="max-width:42em">As I have already introduced, my name Mikiyas Fechasa and I am a highschool student trying to present something most of see in the news in a youngsters perspective. As an 18 years old man, I have come to realize the continuous change which all humans including me are visualizing in front of us. but if we don't keep up with the continuous change around the world, it becomes hard for us to realize where we are or what we have accomplished. This is the reason I created this journal, to spread the news of the new world and for people to keep up with how much the world has changed. JEEDS publishes open-access, peer-reviewed research on cooperation between Ethiopia and Russia, with attention to evidence, transparency and benefits for Ethiopian citizens. Scope: energy, trade, agriculture, industry, technology, education and diplomacy.</p><h2>Editorial board</h2>${board()}<h2 style="margin-top:28px">Publisher, affiliation and contact</h2>${pubBlock()}<p><a class="btn" href="#/contact">Contact us</a></p></div>`},
authors(){const d=(t,c)=>`<details><summary>${t}</summary><p>${c}</p></details>`;return `<div class="w" style="padding-top:28px;max-width:760px"><h1>For authors and reviewers</h1><p>Edit these sample policies to match your journal before launch.</p><a class="btn" href="mailto:${PUB.edmail}?subject=Submission">Submit a manuscript</a>${d('Author guidelines','Manuscripts up to 8,000 words, abstract under 250 words, 4–6 keywords, references in APA 7th edition, data sources named.')}${d('Article types','Research article, policy analysis, feature analysis, commentary, perspective, news analysis.')}${d('Publication fees','No article processing charge during the launch phase (placeholder).')}${d('Copyright and licensing','© 2026 '+PUB.publisher+'. Licensed under CC BY 4.0. Authors keep copyright of their work and grant the journal first publication under the CC BY 4.0 license.')}${d('Policies','Double-blind peer review, conflict-of-interest disclosure, plagiarism screening, correction and retraction procedures, ethical use of AI tools.')}${d('Reviewer guidelines','Assess originality, evidence, methods and clarity within 21 days; declare conflicts; keep manuscripts confidential; give constructive, specific comments.')}</div>`},
resources(){return `<div class="w" style="padding-top:28px;max-width:760px"><h1>Resources</h1><h2>Citation guide</h2><p>Every article page gives an APA reference and a downloadable BibTeX record.</p><pre>${cite(A[0])}</pre><button class="btn sm" id="ba">Download all citations (BibTeX)</button><h2 style="margin-top:28px">Accessibility</h2><p>The site uses semantic headings, keyboard navigation, visible focus, a skip link, dark mode, respect for reduced motion and print-ready article pages. Report barriers to the editorial team.</p></div>`}};
function board(){const R=['Managing Editor','Associate Editor, Energy','Associate Editor, Economy','Associate Editor, Technology','Associate Editor, Policy'],av='<img class="av" src="avatar.svg" alt="" width="56" height="56">';return '<div class="board"><div>'+av+'<b>'+PUB.eic+'</b><div class="m">Editor-in-Chief<br>'+PUB.aff+', '+PUB.country+'</div></div>'+R.map(r=>`<div>${av}<b>Name to add</b><div class="m">${r}<br>Affiliation to add</div></div>`).join('')+'</div>'}
function route(){const h=location.hash.slice(2)||'',[p,q]=h.split('?'),[k,arg]=p.split('/');seo();document.title=J.n;const fn=k=='search'?'articles':k||'home';M.innerHTML=(pages[fn]||pages.home)(fn=='article'?arg:q);document.querySelectorAll('nav a').forEach(a=>a.toggleAttribute('aria-current',a.hash=='#/'+fn));scrollTo(0,0);M.focus({preventScroll:true});
['ms','af'].forEach(id=>{const f=$('#'+id);if(f)f.onsubmit=e=>{e.preventDefault();const u=new URLSearchParams(new FormData(f));[...u].forEach(([a,b])=>b||u.delete(a));location.hash='#/articles?'+u}});
const a=A.find(x=>x.s==arg);if(fn=='article'&&a){$('#cc').onclick=e=>{navigator.clipboard&&navigator.clipboard.writeText(cite(a));e.target.textContent='Copied'};$('#cb').onclick=()=>dl(a.s+'.bib',bib(a));$('#sh').onclick=()=>navigator.share?navigator.share({title:a.t,url:location.href}):navigator.clipboard.writeText(location.href)}
if($('#ba'))$('#ba').onclick=allBib}
const allBib=e=>{e&&e.preventDefault&&e.preventDefault();dl('jeeds-citations.bib',A.map(bib).join('\n\n'))};
$('#bib').onclick=allBib;
$('#hs').onsubmit=e=>{e.preventDefault();location.hash='#/articles?q='+encodeURIComponent(e.target.q.value)};
$('#th').onclick=()=>{const r=document.documentElement,d=getComputedStyle(r).getPropertyValue('--bg').trim()=='#101715';r.dataset.theme=d?'light':'dark'};
addEventListener('scroll',()=>{$('#pg').style.width=(scrollY/Math.max(1,document.body.scrollHeight-innerHeight)*100)+'%'});
addEventListener('hashchange',route);route();