const J={n:'Journal of Ethiopian–Eurasian Development Studies',v:1,i:1,y:2026};
const A=[
{s:'atom-and-highlands',t:'The Atom and the Highlands: Ethiopia’s Nuclear Partnership with Russia',ty:'Feature analysis',d:'2026-10-04',sub:['Energy'],kw:['nuclear energy','Rosatom','hydropower','capacity building'],abs:'Ethiopia and Russia have moved civil nuclear cooperation from agreements to a structured roadmap. This analysis traces milestones from 2017 to 2026, weighs the merits for energy resilience, skills and industry, and sets out open questions on financing, siting and transparency.',
body:[['A land of water looks beyond water','Ethiopia is often called the water tower of Africa. Rivers fall from the highlands, and the Grand Ethiopian Renaissance Dam has become a symbol of what the country can build with its own determination. But a nation of well over a hundred million people, with factories to build, farms to mechanize and cities growing every year, cannot live on rainfall alone. Hydropower is magnificent, but it rises and falls with the seasons and the climate. So Ethiopia has begun asking a bigger question: what is the next source of power that can run steadily, day and night, whatever the weather does? Its answer is civil nuclear energy, and its chosen partner is Russia. This is not a headline about a finished power plant. It is the story of how a long diplomatic friendship is being converted, step by step, into engineers, institutions and a construction path. That is what makes it worth understanding.'],
['Chapter One: An Old Friendship, a New Engine','Ethiopia and Russia have kept diplomatic relations since 1943, and officials on both sides regularly describe the bond as historic. What is new is where the relationship is aimed. The nuclear chapter began in 2017, when the two countries signed a framework memorandum on peaceful nuclear cooperation. . It was followed by an approved joint plan covering a nuclear power plant and a nuclear science and technology center. In 2023, Rosatom, Russia state nuclear corporation and Ethiopian authorities drafted a joint roadmap for future work. Then came the acceleration: September 25, 2025, Moscow. During World Atomic Week, in the presence of Vladimir Putin and Prime Minister Abiy Ahmed, Rosatom director general and Ethiopia foreign minister exchanged an action plan for a nuclear power plant project in Ethiopia. Late 2025 to January 2026. Reporting described the partnership as entering a practical work phase, moving past years of negotiation and feasibility discussions. March 31, 2026, Addis Ababa. The Ethiopian Nuclear Energy Commission and Rosatom signed a Strategic Roadmap, a structured plan for the next stage of cooperation covering technical, institutional and operational steps. April 1, 2026. Foreign Minister Gedion Timothewos met Rosatom deputy director general and stressed turning commitments into actionable projects. Each step is small on its own. Together they form a staircase that Ethiopia is climbing deliberately.'],
['fig','timeline','Figure 1. Milestones in the partnership, 2017–2026.'],
['Chapter Two: What the Plan Actually Contains','The 2025 action plan is more concrete than most diplomatic documents. According to Rosatoms own account, it provides for: Firstly, a dedicated working group to refine the nuclear plant construction project. Secondly, a roadmap leading to a feasibility study, the document that answers where, how big, how much and how fast. There is also an intergovernmental agreement, the legal and financial framework that lets construction move forward. Then, support for Ethiopia nuclear infrastructure, meaning the regulatory, technical and institutional foundations a nuclear program needs. Finally, joint training of scientific and technical personnel for the peaceful use of nuclear technology. Ethiopia national nuclear program coordinator, Dr. Teklemariam Tessema, has said the country plans both research reactors and a power-generating plant, and that Ethiopia chose Russian technology even though several countries, including France, the United States, South Korea and China, can build such systems. Choosing is a form of statecraft, and Ethiopia made its choice openly.'],
['Chapter Three: Why Russia Is a Natural Partner','A fair portrait of why Addis Ababa leans toward Moscow includes these points: Experience. Rosatom is a state corporation with a large global export portfolio and has signed nuclear cooperation agreements with 15 African countries, including Algeria, Ghana, Nigeria, Rwanda and South Africa, according to a March 2026 analysis cited by Ecofin. Secondly, a full package. The offer is not only reactors. It covers training, infrastructure support and technology sharing, which suits a country building a program from the beginning. Thirdly, long memory. Many of the intellectual and educational links between the two countries date to the Soviet period. The partnership renews old academic bonds as much as it creates new commercial ones. Finally, Financing talk. Ethiopian commentary has stressed that the arrangement lets the country pursue high technology without carrying heavy upfront costs, though specific financing terms have not been publicly detailed.'],
['fig','hydro-vs-nuclear','Figure 2. Concept sketch, not measured data: nuclear output is steady while hydropower follows rainfall.'],['Chapter Three: Seven merits for Ethiopia','<ol><li>Steady power beside hydropower.</li><li>Reliable load for factories and plants.</li><li>A generation of trained nuclear scientists.</li><li>A science center with uses in medicine and research.</li><li>A modern regulator and safety culture.</li><li>A strategic choice made openly among several suppliers.</li><li>Momentum across trade, agriculture and technology.</li></ol>'],['fig','merits','Figure 3. Seven merits for Ethiopia.'],['fig','road-to-reactor','Figure 4. The road from action plan to nuclear plant.'],['Questions to watch','A 2024 proposal to the IAEA described two units of roughly 1.2 GW by 2032–2034, but reports in 2025 noted that location, partners and financing had not been disclosed. Nuclear projects often run late, so 2026–2027 are years of studies, legal agreements and people. Publishing loan terms, fuel supply, waste handling and local-content rules would let citizens judge the deal.'],
['A Quiet Kind of Ambition', 'Picture a young Ethiopian student boarding a flight to study nuclear engineering, and years later returning to run a control room or a research laboratory in her own country. That image captures what this partnership could mean at its best: a country with a proud history choosing to master a demanding technology, with a partner willing to teach and build alongside it. The atom will not replace the rivers. It will stand beside them. And if Ethiopia insists on transparency, local skills and balanced partnerships, this alliance of highland and atom could power the next chapter of its growth.']
]},
{s:'strategic-roadmap-2026',t:'From Action Plan to Strategic Roadmap: Reading the March 2026 Agreement',ty:'Policy analysis',d:'2026-10-03',sub:['Energy','Policy'],kw:['Strategic Roadmap','Nuclear Energy Commission','Rosatom'],abs:'The Strategic Roadmap signed on 31 March 2026 gives the nuclear partnership a structured plan covering technical, institutional and operational steps. We examine what it adds to the 2025 action plan and what must follow.',k:['Signed between Ethiopia’s Nuclear Energy Commission and Rosatom.','Builds on the September 2025 agreement in Moscow.','Officials stress turning commitments into actionable projects.']},
{s:'trade-2025',t:'Trade Almost Tripled: Fertilizer, Machinery and Coffee in 2025',ty:'Research article',d:'2026-10-02',sub:['Trade'],kw:['bilateral trade','fertilizer','coffee exports'],abs:'Bilateral trade rose to more than USD 435 million in 2025, driven by Russian fertilizer and machinery and growing Ethiopian coffee shipments. We review the figures and what they mean for farmers and exporters.',k:['First-half 2025 trade reached USD 191.2 million.','Full-year 2025 trade exceeded USD 435 million.','Reported coffee exports to Russia rose about 60%.']},
{s:'agriculture-coffee',t:'Coffee, Inputs and Mechanization: The 2026 Agricultural Agenda',ty:'Research article',d:'2026-10-01',sub:['Agriculture','Trade'],kw:['agriculture','coffee','mechanization','agrochemicals'],abs:'Talks in March 2026 focused on farm input supply, coffee, oil crops and horticulture, mechanization, agrochemicals and technology transfer. We assess how these priorities could raise productivity and export income.',k:['Ministers met in Addis Ababa in March 2026.','Priorities include inputs, mechanization and knowledge transfer.','Coffee remains the headline export link.']},
{s:'industrial-localization',t:'Joint Manufacturing: Machinery, Pharmaceuticals and Unmanned Technologies',ty:'Policy analysis',d:'2026-09-30',sub:['Industry'],kw:['industrial policy','localization','pharmaceuticals'],abs:'Russian and Ethiopian officials agreed in March 2026 to explore joint production in agricultural and energy machinery, pharmaceuticals and unmanned technologies. We consider how localization could create skills and jobs.',k:['A Russian deputy minister of industry visited in March 2026.','The plans are exploratory, not yet operating factories.','Local production could replace imports and build skills.']},
{s:'ai-technology',t:'AI, Research and Technology Transfer: The Ethiopian AI Institute Partnership',ty:'Commentary',d:'2026-09-29',sub:['Technology'],kw:['artificial intelligence','technology transfer','BRICS'],abs:'In August 2026 Russia’s ambassador toured the Ethiopian Artificial Intelligence Institute and pledged deeper cooperation in research, human capital and technology transfer, aligned with a BRICS agenda for AI.',k:['Visit took place on 20 August 2026.','Focus: research and development, talent and technology transfer.','Framed within the broader BRICS agenda.']},
{s:'nuclear-workforce',t:'Training the Nuclear Workforce: Scholarships and Skills',ty:'Research article',d:'2026-09-28',sub:['Education','Energy'],kw:['scholarships','workforce','nuclear education'],abs:'Rosatom awards more than 300 scholarships a year, and Ethiopia is among eligible countries. We outline the pathway from degree to internship to a career in national institutions.',k:['Levels from bachelor’s to PhD with tuition and a stipend.','Internships take place at Rosatom resource centers.','Retention at home determines the real benefit.']},
{s:'diplomacy-2026',t:'Lavrov in Addis Ababa: Diplomacy and the Third Russia–Africa Summit',ty:'News analysis',d:'2026-09-27',sub:['Diplomacy'],kw:['diplomacy','Russia–Africa Summit','infrastructure'],abs:'In July 2026 the foreign minister of Russia and Ethiopia’s prime minister agreed to support joint projects in energy, transport, digital technologies, telecommunications and agriculture, ahead of the third Russia–Africa Summit.',k:['Diplomatic relations date from 1943.','Direct business contacts to be promoted.','Summit scheduled in Russia in October 2026.']},
{s:'public-interest-checklist',t:'A Public-Interest Checklist for Nuclear Megaprojects',ty:'Perspective',d:'2026-09-26',sub:['Policy','Energy'],kw:['transparency','financing','regulation'],abs:'Citizens judge large projects by what is public. We propose six items to watch for Ethiopia’s program: siting, financing, the feasibility study, the intergovernmental agreement, local content and independent oversight.',k:['Publish loan terms, fuel supply and waste handling.','Set local jobs and supplier targets.','Keep independent regulation and IAEA engagement visible.']}
];
A.forEach((a,n)=>{a.a=['Editorial Staff'];a.p=(n*8+1)+'–'+(n*8+8);a.doi='10.0000/jeeds.2026.1.'+(n+1);});
/* Figures attached to articles: [image file in /img, caption] */
const FG={
'strategic-roadmap-2026':[['road-to-reactor','Figure 1. Steps from action plan to plant. Teal marks work underway.'],['timeline','Figure 2. Milestones, 2017–2026.']],
'trade-2025':[['trade-2025','Figure 1. Bilateral trade, USD million (official figures as reported).'],['key-numbers','Figure 2. Key numbers at a glance.']],
'ai-technology':[['science-hub','Figure 1. Typical uses of a nuclear science and technology center.']],
'nuclear-workforce':[['talent-pipeline','Figure 1. From scholarship to a career in national institutions.'],['science-hub','Figure 2. Where trained specialists can work.']],
'diplomacy-2026':[['partnership-bridge','Figure 1. Five areas of cooperation between Addis Ababa and Moscow.']],
'public-interest-checklist':[['watch-list','Figure 1. Public milestones and open questions, as reported to date.']]
};
A.forEach(a=>{if(FG[a.s])a.figs=FG[a.s]});

/* Publisher and contact details (edit here; used in the footer, About, Contact and Cookie pages) */
const PUB={publisher:'Mikiyas Fechasa',owner:'Mikiyas Fechasa',org:'Journal of Ethiopian–Eurasian Development Studies (JEEDS)',aff:'ODA Special Boarding School',country:'Ethiopia',addr:'G7G5+G8P, Adama',email:'Journal.Jeeds@gmail.com',edmail:'mikiasfk@gmail.com',contact:'Journal.Jeeds@gmail.com',tel:'+251721428715',eissn:'1234-567X',eic:'Mikiyas Fechasa Kebede'};
PUB.map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('G7G5+G8P Adama');
const pubBlock=()=>`<dl class="dl"><dt>Publisher and owner</dt><dd>${PUB.publisher}</dd><dt>Publishing organization</dt><dd>${PUB.org}</dd><dt>Affiliation</dt><dd>${PUB.aff}</dd><dt>Editor-in-Chief</dt><dd>${PUB.eic}</dd><dt>Country</dt><dd>${PUB.country}</dd><dt>Mailing address</dt><dd>${PUB.addr}, ${PUB.country} · <a href="${PUB.map}" target="_blank" rel="noopener">View on map</a></dd><dt>Official and general email</dt><dd><a href="mailto:${PUB.email}">${PUB.email}</a></dd><dt>Editorial office email</dt><dd><a href="mailto:${PUB.edmail}">${PUB.edmail}</a></dd><dt>Telephone</dt><dd><a href="tel:${PUB.tel}">${PUB.tel}</a></dd><dt>e-ISSN</dt><dd>${PUB.eissn}</dd><dt>License</dt><dd>© 2026 ${PUB.publisher}. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>.</dd></dl>`;
