/* Contact page, Cookie policy page and cookie notice */
pages.contact=()=>`<div class="w" style="padding-top:28px;max-width:820px"><h1>Contact</h1><p class="m">Write to us about submissions, reviewing, corrections or general questions.</p>${pubBlock()}<h2 style="margin-top:32px">Send a message</h2><form class="f" id="cf"><label for="cn">Your name</label><input id="cn" name="n" autocomplete="name"><label for="cm">Your email</label><input id="cm" name="m" type="email" autocomplete="email"><label for="cs">Subject</label><input id="cs" name="s"><label for="cx">Message</label><textarea id="cx" name="x" rows="6"></textarea><p id="cr" class="err" hidden></p><p><button class="btn">Open email draft</button></p><p class="m">This opens your email app, addressed to ${PUB.contact}.</p></form></div>`;
function bindContact(){const f=$('#cf');if(!f)return;f.onsubmit=ev=>{ev.preventDefault();const v=Object.fromEntries(new FormData(f)),er=$('#cr');if(!v.n.trim()||!/^\S+@\S+\.\S+$/.test(v.m)||!v.x.trim()){er.textContent='Enter your name, a valid email and a message.';er.hidden=false;return}er.hidden=true;location.href='mailto:'+PUB.contact+'?subject='+encodeURIComponent(v.s||'Message from the JEEDS website')+'&body='+encodeURIComponent(v.x+'\n\n'+v.n+' ('+v.m+')')}}
pages.cookies=()=>`<div class="w" style="padding-top:28px;max-width:820px"><h1>Cookie policy</h1><p class="m">Last updated 4 October 2026</p><p>This page explains how ${PUB.org} uses cookies and similar browser storage.</p><div class="abs"><b>In short.</b> This site does not set cookies of its own. It uses no analytics, advertising or cross-site tracking. A few settings are kept in your browser storage so the site can remember them, and you can erase them at any time.</div>
<h2 style="margin-top:28px">Necessary</h2><p>Authentication, security and essential preferences. The journal has no login accounts yet, so no authentication or security cookies are used. If author, reviewer or editor dashboards are added, their session cookies will be listed here.</p><div class="tw"><table><tr><th>Name</th><th>Type</th><th>Purpose</th><th>Kept</th></tr><tr><td>jck</td><td>Browser storage</td><td>Remembers that you closed the cookie notice</td><td>Until you clear it</td></tr></table></div>
<h2>Analytics</h2><p>Not used. If we adopt a tool such as Google Analytics or Matomo, we will list its cookies here, explain what they measure and ask for your consent first.</p>
<h2>Functional</h2><p>These remember your settings and stay on your device. They are never sent to us.</p><div class="tw"><table><tr><th>Name</th><th>Type</th><th>Purpose</th><th>Kept</th></tr><tr><td>jsv</td><td>Browser storage</td><td>Your reading list</td><td>Until you clear it</td></tr><tr><td>jv</td><td>Browser storage</td><td>Article view counts for the "Most read" sort on your device</td><td>Until you clear it</td></tr><tr><td>jz</td><td>Browser storage</td><td>Your chosen article text size</td><td>Until you clear it</td></tr><tr><td>wb…</td><td>Session storage</td><td>Temporary copy of World Bank data you loaded</td><td>Until you close the tab</td></tr></table></div>
<h2>Marketing</h2><p>Not used. The site shows no advertising and does not build advertising profiles.</p>
<h2>Third-party services</h2><p>Some pages contact outside services, which can see your IP address and browser details when your browser connects to them: Google Fonts (page typefaces), the World Bank (Data page), OpenAlex (Literature page) and Crossref (DOI lookup). Each follows its own privacy policy. If fonts are blocked, the site falls back to system fonts.</p>
<h2>Your choices</h2><p>You can erase everything this site stored in your browser with the button below, or manage cookies and site data in your browser settings.</p><p><button class="btn o" id="cl">Clear stored data</button> <span id="cm2" class="m" aria-live="polite"></span></p>
<h2>Contact</h2><p>Questions about this policy: <a href="mailto:${PUB.contact}">${PUB.contact}</a>, ${PUB.addr}, ${PUB.country}.</p></div>`;
function bindCookies(){const b=$('#cl');if(b)b.onclick=()=>{['jck','jsv','jv','jz'].forEach(k=>localStorage.removeItem(k));sessionStorage.clear();$('#cm2').textContent='Stored data cleared.'}}
(()=>{if(localStorage.getItem('jck'))return;const c=document.createElement('div');c.className='ck';c.setAttribute('role','region');c.setAttribute('aria-label','Cookie notice');c.innerHTML='<span>This site uses no tracking cookies. It stores a few settings, such as your reading list, in your browser.</span><a href="#/cookies">Cookie policy</a><button class="btn sm">OK</button>';c.querySelector('button').onclick=()=>{localStorage.setItem('jck','1');c.remove()};document.body.append(c)})();
